version: '3.3'
services:
  db_current_diploma:
    platform: linux/x86_64
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: 'diplomaBDS'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      POSTGRES_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - /home/tt/Desktop/docker/postgressvar/lib/postgress
    # Application
  diploma-application:
      container_name: diploma-be
      image: diploma-be:latest
      build:
        context: ..
        dockerfile: docker/dockerfile/diploma-back
      ports:
        - "8083:8080"
      environment:
        MYSQL_HOST: localhost
      depends_on:
        - db_current_diploma
# Names our volume
volumes:
  my-db:
